edgexfoundry/edgex-examples

README.md

Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
What kind of change does this PR introduce?
not applicable
Issue Number:
#2 
initial readme
no
no

addition of readme with purpose and examples rules

---

application-services/custom/advanced-filter-convert-publish/go.mod
application-services/custom/advanced-target-type/go.mod
application-services/custom/aws-export/Dockerfile
application-services/custom/aws-export/go.mod
application-services/custom/azure-export/go.mod
application-services/custom/cloud-event/Dockerfile
application-services/custom/cloud-event/go.mod
application-services/custom/json-logic/go.mod
application-services/custom/secrets/Dockerfile
application-services/custom/secrets/go.mod
application-services/custom/send-command/go.mod
application-services/custom/simple-cbor-filter/go.mod
application-services/custom/simple-filter-xml-http/go.mod
application-services/custom/simple-filter-xml-mqtt/go.mod
application-services/custom/simple-filter-xml/Dockerfile
application-services/custom/simple-filter-xml/go.mod

What kind of change does this PR introduce?
Issue Number: #8

build(app-services): Upgrade to use Go 1.15.x

---

.github/semantic.yml

removed paren comments that were causing scopes to fail
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
fix semantic.yml in order to provide proper scopes that won't fail semantic conventional commit bot

fix: clean up scopes so they work with bot

---

application-services/custom/advanced-filter-convert-publish/go.mod
application-services/custom/advanced-target-type/go.mod
application-services/custom/aws-export/go.mod
application-services/custom/azure-export/go.mod
application-services/custom/cloud-event/go.mod
application-services/custom/fledge-export/go.mod
application-services/custom/json-logic/go.mod
application-services/custom/secrets/go.mod
application-services/custom/send-command/go.mod
application-services/custom/simple-cbor-filter/go.mod
application-services/custom/simple-filter-xml-http/go.mod
application-services/custom/simple-filter-xml-mqtt/go.mod
application-services/custom/simple-filter-xml/go.mod

Examples use pre-hanoi SDK
Examples now use release Hanoi SDK (1.3.0)
- {x] No

build: Update App Service examples to use released 1.3.0 (hanoi) SDK

---

deployment/kubernetes/README.md
deployment/kubernetes/clean-cache.sh
deployment/kubernetes/clean-volumes.sh
deployment/kubernetes/k8s-geneva-redis-no-secty.yml
deployment/kubernetes/k8s-hanoi-redis-no-secty.yml

with single node deployments for Geneva and Hanoi
includes instructions on how to use with MicroK8s
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
None
Added example K8s deployment

feat(deploy): addition of K8s deployment example

---

application-services/custom/custom-trigger/Dockerfile
application-services/custom/custom-trigger/Makefile
application-services/custom/custom-trigger/README.md
application-services/custom/custom-trigger/go.mod
application-services/custom/custom-trigger/main.go
application-services/custom/custom-trigger/res/configuration.toml

Introduce an example for the custom trigger functionality introduced to
the SDK in https://github.com/edgexfoundry/app-functions-sdk-go/pull/587
#29
Introduces an example service that uses a custom trigger to read messages from stdin.

feat(app): Add Custom Trigger Example

---

application-services/custom/custom-trigger/main.go

Add missing goroutine around processing loop for stdin trigger
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
#35
Wraps processing loop for example stdin trigger in a goroutine.

fix(app): Custom Trigger Processing Loop

---

application-services/custom/aws-export/README.md

docs: format toml configuration 

---

application-services/custom/simple-filter-xml-http/App Services.postman_collection.json
application-services/custom/simple-filter-xml-http/Makefile
application-services/custom/simple-filter-xml-http/go.mod
application-services/custom/simple-filter-xml-http/main.go
application-services/custom/simple-filter-xml-http/res/configuration.toml
application-services/custom/simple-filter-xml-mqtt/App Services.postman_collection.json
application-services/custom/simple-filter-xml-mqtt/Makefile
application-services/custom/simple-filter-xml-mqtt/go.mod
application-services/custom/simple-filter-xml-mqtt/main.go
application-services/custom/simple-filter-xml-mqtt/res/configuration.toml
application-services/custom/simple-filter-xml/go.mod
application-services/custom/simple-filter-xml/main.go
application-services/custom/simple-filter-xml/res/configuration.toml

app-simple-filter-xml-http & app-simple-filter-xml-mqtt not migrated to V2
app-simple-filter-xml migration needs some tweaks
app-simple-filter-xml-http & app-simple-filter-xml-mqtt now migrated to V2
completed tweaks to previous migration of app-simple-filter-xml 

feat: Migrate app-simple-filter-xml export examples to V2

---

application-services/custom/advanced-target-type/functions/convert.go
application-services/custom/advanced-target-type/functions/output.go
application-services/custom/advanced-target-type/go.mod
application-services/custom/advanced-target-type/main.go
application-services/custom/advanced-target-type/res/configuration.toml

Update TargetType example to use version 2 SDK
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>

feat(app): Update TargetType Example to v2 SDK

---

application-services/custom/simple-cbor-filter/Device Simple Switch commands.postman_collection.json
application-services/custom/simple-cbor-filter/Makefile
application-services/custom/simple-cbor-filter/README.md
application-services/custom/simple-cbor-filter/go.mod
application-services/custom/simple-cbor-filter/main.go
application-services/custom/simple-cbor-filter/res/configuration.toml

simple-cbor-filter not migrated to V2
simple-cbor-filter now migrated to V2

feat: Migrate simple-cbor-filter to V2

---

application-services/custom/advanced-target-type/main.go
application-services/custom/cloud-event/Dockerfile
application-services/custom/cloud-event/go.mod
application-services/custom/cloud-event/main.go
application-services/custom/cloud-event/pkg/transforms/conversion.go
application-services/custom/cloud-event/pkg/transforms/conversion_test.go
application-services/custom/cloud-event/res/configuration.toml
application-services/custom/custom-trigger/main.go

feat(app): Update Cloud Event Example to 2.0 SDK 

---

application-services/custom/secrets/Dockerfile
application-services/custom/secrets/functions/getsecrets.go
application-services/custom/secrets/go.mod
application-services/custom/secrets/main.go
application-services/custom/secrets/res/configuration.toml

Update secrets example to released v2.0.0 SDK
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>

feat(app): Update Secret Example to v2 SDK

---

application-services/custom/json-logic/go.mod
application-services/custom/json-logic/main.go
application-services/custom/json-logic/res/configuration.toml

Use released v2 SDK in json-logic example
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>

feat(app): Update json-logic example to v2

---

application-services/configurable/app-service-configurable-ibm/README.md
application-services/configurable/app-service-configurable-ibm/res/ibm-mqtt-export/configuration.toml

ibm-mqtt-export profile example not migrated to V2
ibm-mqtt-export profile example is now migrated to V2

feat: Migrate the ibm-mqtt-export profile example to V2

---

deployment/raspberry-pi-4/10_install_ubuntu.md

fixing one little typo in 10_install_ubuntu.md
no testing requiered

fix: typo in 10_install_ubuntu.md

---

application-services/custom/custom-trigger/go.mod
application-services/custom/custom-trigger/main.go

Use new MessageReceived function on trigger config to hand off to
pipeline WITHOUT context construction to take advantage of multiple
pipelines configured if needed

feat(app): Update Custom Trigger Example

---

deployment/helm/README.md

Updated to point to public edgex examples
Documentation change only, no code change

fix: link in README.md to helm chart is wrong

---

application-services/custom/custom-trigger/main.go

Update custom trigger example to use response handler.

feat(app): Custom Trigger Response Handler

---

deployment/helm/Chart.yaml
deployment/helm/README.md
deployment/helm/values.yaml

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
```
helm install edgex-kamakura . --namespace edgex --set edgex.secure.enabled=true
```

feat: Update helm chart to use Kamakura (2.2.0) tagged images

---

deployment/helm/README.md

Signed-off-by: Eshe N. Pickett eshe.n.pickett@intel.com
View README.md in deployment/helm

(docs): changes helm installation instructions

---

deployment/helm/templates/edgex-security-bootstrapper/edgex-security-bootstrapper-deployment.yaml
deployment/helm/templates/edgex-security-secretstore-setup/edgex-security-secretstore-setup-deployment.yaml
deployment/helm/values.yaml

fixes: edgex-go issue [ #3851](https://github.com/edgexfoundry/edgex-go/issues/3851) to remove work-around
related PR from edgex-go: [#4085](https://github.com/edgexfoundry/edgex-go/pull/4085) 
Signed-off-by: Valina Li <valina.li@intel.com>

fix: fixed security-bootstrapper Docker volume init semantics

---

security/remote_devices/spiffe_and_ssh/README.md

fixed: #112
Signed-off-by: Valina Li <valina.li@intel.com>

fix: Broken link to RemoteDeviceServices

---

application-services/custom/camera-management/Dockerfile

- **N/A** I have added unit tests for the new feature or bug fix (if not, why?)
```shell
cd application-services/custom/camera-management
make docker
```

Fix Camera Mangement Docker Build

---

application-services/custom/camera-management/Dockerfile

Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
- N/AI have added unit tests for the new feature or bug fix (if not, why?)

fix: remove vendor folder from build

---

deployment/helm/templates/edgex-appservice-rules/edgex-app-rules-engine-deployment.yaml
deployment/helm/templates/edgex-consul/edgex-consul-deployment.yaml
deployment/helm/templates/edgex-core-command/edgex-core-command-deployment.yaml
deployment/helm/templates/edgex-core-data/edgex-core-data-deployment.yaml
deployment/helm/templates/edgex-device-rest/edgex-device-rest-deployment.yaml
deployment/helm/templates/edgex-device-virtual/edgex-device-virtual-deployment.yaml
deployment/helm/templates/edgex-ekuiper/edgex-ekuiper-deployment.yaml
deployment/helm/templates/edgex-metadata/edgex-core-metadata-deployment.yaml
deployment/helm/templates/edgex-redis/edgex-redis-deployment.yaml
deployment/helm/templates/edgex-security-secretstore-setup/edgex-security-secretstore-setup-deployment.yaml
deployment/helm/templates/edgex-support-notifications/edgex-support-notifications-deployment.yaml
deployment/helm/templates/edgex-support-scheduler/edgex-support-scheduler-deployment.yaml
deployment/helm/templates/edgex-system/edgex-sys-mgmt-agent-deployment.yaml
deployment/helm/templates/edgex-vault/edgex-vault-deployment.yaml
deployment/helm/values.yaml

feat: Added support for additional storage engines

---

deployment/helm/values.yaml

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
Closes #126 

build: Update HELM Chart to Levski released images

---

deployment/helm/templates/edgex-ui/edgex-ui-deployment.yaml

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
Without this change, edgex-ui deployment fails its health check.

fix: EdgeX UI in kubernetes was not binding container network IF

---

deployment/helm/templates/edgex-consul/edgex-consul-deployment.yaml
deployment/helm/templates/edgex-device-onvif-camera/edgex-device-usb-camera-deployment.yaml
deployment/helm/templates/edgex-device-onvif-camera/edgex-device-usb-camera-service.yaml
deployment/helm/templates/edgex-device-usb-camera/edgex-device-onvif-camera-deployment.yaml
deployment/helm/templates/edgex-device-usb-camera/edgex-device-onvif-camera-service.yaml
deployment/helm/templates/edgex-pv.yaml
deployment/helm/templates/edgex-pvc.yaml
deployment/helm/templates/edgex-security-secretstore-setup/edgex-security-secretstore-setup-deployment.yaml
deployment/helm/values.yaml

feat: Added support for onvif and usb camera

---

deployment/helm/templates/edgex-modbus-simulator/edgex-modbus-simulator-deployment.yaml
deployment/helm/templates/edgex-modbus-simulator/edgex-modbus-simulator-service.yaml
deployment/helm/values.yaml

feat: Added support for modbus-simulator

---

deployment/helm/templates/edgex-device-mqtt/edgex-device-mqtt-deployment.yaml
deployment/helm/templates/edgex-device-mqtt/edgex-device-mqtt-service.yaml
deployment/helm/templates/edgex-mqtt-broker/edgex-mqtt-broker-deployment.yaml
deployment/helm/templates/edgex-mqtt-broker/edgex-mqtt-broker-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-mqtt and mqtt-broker

---

deployment/helm/templates/edgex-device-modbus/edgex-device-modbus-deployment.yaml
deployment/helm/templates/edgex-device-modbus/edgex-device-modbus-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-modbus

---

deployment/helm/templates/edgex-device-bacnet/edgex-device-bacnet-deployment.yaml
deployment/helm/templates/edgex-device-bacnet/edgex-device-bacnet-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-bacnet

---

deployment/helm/templates/edgex-device-snmp/edgex-device-snmp-deployment.yaml
deployment/helm/templates/edgex-device-snmp/edgex-device-snmp-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-snmp

---

deployment/helm/templates/edgex-device-rfid-llrp/edgex-device-rfid-llrp-deployment.yaml
deployment/helm/templates/edgex-device-rfid-llrp/edgex-device-rfid-llrp-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-rfid-llrp

---

deployment/helm/templates/edgex-device-gpio/edgex-device-gpio-deployment.yaml
deployment/helm/templates/edgex-device-gpio/edgex-device-gpio-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for ds-gpio

---

deployment/helm/templates/edgex-app-http-export/edgex-app-http-export-deployment.yaml
deployment/helm/templates/edgex-app-http-export/edgex-app-http-export-service.yaml
deployment/helm/templates/edgex-app-mqtt-export/edgex-app-mqtt-export-deployment.yaml
deployment/helm/templates/edgex-app-mqtt-export/edgex-app-mqtt-export-service.yaml
deployment/helm/values.yaml

feat: Add support in helm for asc-mqtt and asc-httpexport

---

deployment/helm/templates/edgex-app-metrics-influxdb/edgex-app-metrics-influxdb-deployment.yaml
deployment/helm/templates/edgex-app-metrics-influxdb/edgex-app-metrics-influxdb-service.yaml
deployment/helm/templates/edgex-app-rfid-llrp-inventory/edgex-app-rfid-llrp-inventory-deployment.yaml
deployment/helm/templates/edgex-app-rfid-llrp-inventory/edgex-app-rfid-llrp-inventory-service.yaml
deployment/helm/templates/edgex-app-sample/edgex-app-sample-deployment.yaml
deployment/helm/templates/edgex-app-sample/edgex-app-sample-service.yaml
deployment/helm/templates/edgex-pv.yaml
deployment/helm/templates/edgex-pvc.yaml
deployment/helm/values.yaml

feat: Add support in helm for asc-sample, asc-metrics, and as-llrp

---

deployment/helm/templates/edgex-ui/edgex-ui-service.yaml

fix: added service for edgex-ui

---

deployment/helm/templates/edgex-app-external-mqtt-trigger/edgex-app-external-mqtt-trigger-deployment.yaml
deployment/helm/templates/edgex-app-http-export/edgex-app-http-export-deployment.yaml
deployment/helm/templates/edgex-device-bacnet/edgex-device-bacnet-deployment.yaml
deployment/helm/templates/edgex-device-gpio/edgex-device-gpio-deployment.yaml
deployment/helm/templates/edgex-device-modbus/edgex-device-modbus-deployment.yaml
deployment/helm/templates/edgex-device-mqtt/edgex-device-mqtt-deployment.yaml
deployment/helm/templates/edgex-device-onvif-camera/edgex-device-onvif-camera-deployment.yaml
deployment/helm/templates/edgex-device-rest/edgex-device-rest-deployment.yaml
deployment/helm/templates/edgex-device-rfid-llrp/edgex-device-rfid-llrp-deployment.yaml
deployment/helm/templates/edgex-device-snmp/edgex-device-snmp-deployment.yaml
deployment/helm/templates/edgex-device-usb-camera/edgex-device-usb-camera-deployment.yaml
deployment/helm/templates/edgex-device-virtual/edgex-device-virtual-deployment.yaml
deployment/helm/templates/edgex-security-bootstrapper/edgex-security-bootstrapper-deployment.yaml
deployment/helm/templates/edgex-vault/edgex-vault-deployment.yaml
deployment/helm/values.yaml

fix: Updated  health checks to appropriate protocol

---

application-services/custom/camera-management/README.md

- [N/A] I have added unit tests for the new feature or bug fix (if not, why?)
- [N/A] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

docs: add link to camera app example video

---

application-services/configurable/app-service-configurable-ibm/res/ibm-mqtt-export/configuration.yaml

fix: Address missed V3 migration of InsecureSecrets

---

deployment/helm/values.yaml

feat: Update to 3.0.0 images in helm values.yaml

---

README.md

docs: Add repo main branch warning

---

application-services/custom/influxdb-export/main.go

fix: Fix issue with wrong name used to load custom config
